### ISSUE TITLE
Shortcuts interfere with default Firefox's shortcuts on Mac

### ISSUE THREAD

**Issue by pdorobisz** [sblask/webextension-tab-deque#11]
### New Issue Checklist (tick off like this: `[x]`)

- [ x] I checked existing issues (open and closed) for possible duplicates

### What is your browser?

- [ x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

enqueue and dequeue commands are assigned cmd+up and cmd+down shortcuts on Mac. Unfortunately, this interferes with FF's default shortcuts (cmd+up: go to the top of the page, cmd+down: go to the bottom of the page). For example pressing cmd+down scrolls page to the bottom and changes tabs.
I would be nice to have option to disable these shortcuts or redefine them.

**Comment by sblask** [comment]
Not possible, but there is a Firefox bug about keyboard shortcuts handling. Who knows when it will be implemented. One of the reason I don't use Firefox anymore. I could change the shortcuts to something else just for Mac. Suggestions?

**Comment by monitorius** [comment]
I have the same problem. If we can't disable one hotkey, maybe it's possible to disable all hotkeys at once from extension settings? If not, I would suggest something like `shift+alt+cmd+up` to prevent interferring with anything

**Comment by pdorobisz** [comment]
I'd prefer removing shortcuts completely.
Other solution would be to introduce an option in plugin's preferences to disable shortcuts. When this option is checked the command shortcut is referring to would simply do nothing. Is it possible? I don't know much about developing plugins.

**Comment by sblask** [comment]
What is the interference actually? Does the original shortcut still work, or not? Because I can make it so the extension still registers its shortcuts but then doesn't actually do anything when they are clicked. This won't help though if the original shortcut is disabled.

**Comment by pdorobisz** [comment]
Yes, original shortcut works. For example after pressing cmd+down tabs will be changed but page will be scrolled down.

**Comment by sblask** [comment]
Fixed with release 2.1.0
