### ISSUE TITLE
Interaction with deferred media autoplay

### ISSUE THREAD

**Issue by tobbez** [sblask/webextension-tab-deque#12]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
Firefox has a feature where playback of audio/video in tabs opened in the background will not start until that tab is activated.

When a tab is closed, Tab Deque detects this and selects the tab which is now at the top of the deque. However, it is not activated until after Firefox has already activated another tab according to its own rules. If that tab has deferred autoplay video/audio content, playback starts in that tab.

If there is a reasonable way for Tab Deque to address this, that would be great.

If it isn't (which may very well be the case), it would be nice if the README acknowledged this.

**Comment by sblask** [comment]
Nothing that can be done but disabling autoplay altogether (I think it's a bad feature anyway). So how about adding this to the README: `If you have autoplay of audio/video content enabled, unexpected tabs might start playing the content as the browsers thinks a different tab has become active`.

**Comment by tobbez** [comment]
Maybe add something at the end saying it can't be fixed, but otherwise that sounds fine.
