### ISSUE TITLE
Cmd-Up/Down scrolls to bottom/top of selected page

### ISSUE THREAD

**Issue by dhduvall** [sblask/webextension-tab-deque#13]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [X] Firefox (59.0.2)
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [X] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

When I hit Cmd-Up, I get to the expected page, but it scrolls me to the bottom. Similarly, Cmd-Down scrolls me to the top.

**Comment by sblask** [comment]
You can disable the shortcut, see #11

**Comment by dhduvall** [comment]
Ah. I don't want to disable the tab-deque shortcut, I want to disable the Firefox shortcut, since Fn-Left/Right gives me top/bottom of page already, but I guess that's not possible?

**Comment by sblask** [comment]
Firefox is really bad when it comes to keyboard configuration. Chromium is better, but I think Vivaldi is best.
