### ISSUE TITLE
[Feature] Stop looping around the tab queue

### ISSUE THREAD

**Issue by amynbe** [sblask/webextension-tab-deque#14]
First thanks for this excellent extension I've been awaiting for years.
Can we have an option to prevent minimising the last tab please? That is, when I'm on the last tab, I want Ctrl+down to have no effect (suggest showing a status message).
Similarly, when I've "maximised" all my tabs, I want Ctrl+up to have no effect, rather than looping to the last tab.

**Comment by sblask** [comment]
You can disable this in the options...

**Comment by amynbe** [comment]
I obviously checked the options before filing this feature request. I'm happy to clarify anything that might be unclear in my first message.

**Comment by sblask** [comment]
Now I get what you mean. You generally want the keyboard shortcuts to work, just not when it's the first/last tab. The problem is: what is first and last? There is no visual indication of the tab order. I think it would be rather confusing. A status message is not an option.

**Comment by amynbe** [comment]
I think you can make an arbitrary choice at browser startup, such as to say
the leftmost tab is the last one. Maybe that's already the case with the
natural order of your current deque implementation (i.e leftmost tab ==
first element of the deque)?
