### ISSUE TITLE
Go to last tab instead of first after restore previous session

### ISSUE THREAD

**Issue by MrGlasspoole** [sblask/webextension-tab-deque#8]
Hi,
if you restore a previous session with allot of tabs and the last one is active and you close it then you jump to the first tab (left).
Is it possible to make it that the last tab (right) is selected?

**Comment by sblask** [comment]
I don't think it's tab deque doing that? Can you try whether it's the same without tab deque?

**Comment by MrGlasspoole** [comment]
I thought you can change that like Tab Mix Plus did it :-(

**Comment by sblask** [comment]
It could, but It won't. Tab Mix Plus did a lot of things, but Tab Deque does only one thing. What happens after a restore is out of scope. If it would even be possible to be done with the new API.
