### ISSUE TITLE
After restore previous session tabs in between are loaded

### ISSUE THREAD

**Issue by MrGlasspoole** [sblask/webextension-tab-deque#9]
Lets say I restore a previous session with this tabs:
Google | DuckDuckGo | Facebook | YouTube | Bing

Bing is active and the other tabs are not loaded.
If i then select Facebook and then close the tab it jumps to Bing as it should but YouTube gets loaded.

**Comment by sblask** [comment]
There is no way of doing something about this. Youtube would have been the next one to get activated, so it gets loaded. No way to cancel that.

**Comment by MrGlasspoole** [comment]
This does not happen in older Firefox versions with Tab Mix Plus.

**Comment by sblask** [comment]
There is only the webextension API left which can't do the same as older APIs. Tab Mix Plus is dead if I understood it. The new API is why.
